import type { LotteryConfig, LotteryType } from '../types/lottery';

export const MESES_DO_ANO = [
  'Janeiro',
  'Fevereiro',
  'Março',
  'Abril',
  'Maio',
  'Junho',
  'Julho',
  'Agosto',
  'Setembro',
  'Outubro',
  'Novembro',
  'Dezembro',
];

export const TIMES_CORACAO = [
  'ABC / RN',
  'América / MG',
  'América / RJ',
  'América / RN',
  'Athletico / PR',
  'Atlético / GO',
  'Atlético / MG',
  'Avaí / SC',
  'Bahia / BA',
  'Botafogo / PB',
  'Botafogo / RJ',
  'Botafogo / SP',
  'Bragantino / SP',
  'Brasil / RS',
  'Ceará / CE',
  'Chapecoense / SC',
  'Corinthians / SP',
  'Coritiba / PR',
  'CRB / AL',
  'Criciúma / SC',
  'Cruzeiro / MG',
  'CSA / AL',
  'Cuiabá / MT',
  'Figueirense / SC',
  'Flamengo / RJ',
  'Fluminense / RJ',
  'Fortaleza / CE',
  'Goiás / GO',
  'Grêmio / RS',
  'Guarani / SP',
  'Internacional / RS',
  'Juventude / RS',
  'Londrina / PR',
  'Náutico / PE',
  'Operário / PR',
  'Palmeiras / SP',
  'Paraná / PR',
  'Paysandu / PA',
  'Ponte Preta / SP',
  'Remo / PA',
  'Sampaio Corrêa / MA',
  'Santa Cruz / PE',
  'Santos / SP',
  'São Paulo / SP',
  'Sport / PE',
  'Vasco da Gama / RJ',
  'Vila Nova / GO',
  'Vitória / BA',
];

export const LOTTERIES_CONFIG: Record<LotteryType, LotteryConfig> = {
  megasena: {
    id: 'megasena',
    slug: 'mega-sena',
    name: 'Mega-Sena',
    fullName: 'Mega-Sena',
    description: 'A maior e mais cobiçada loteria do Brasil com prêmios milionários.',
    primaryColor: '#209869',
    badgeBg: 'bg-emerald-500/10 dark:bg-emerald-400/20 text-emerald-700 dark:text-emerald-300 border-emerald-300 dark:border-emerald-600',
    badgeText: 'text-emerald-700 dark:text-emerald-300',
    ballBg: 'bg-gradient-to-br from-emerald-500 to-emerald-700 text-white shadow-emerald-500/30',
    accentBorder: 'border-emerald-500',
    minNumber: 1,
    maxNumber: 60,
    defaultPickQuantity: 6,
    allowedPickQuantities: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    howToPlay: 'Aposte de 6 a 20 números dos 60 disponíveis no volante. Ganha prêmios quem acertar 6 (Sena), 5 (Quina) ou 4 (Quadra) números.',
    drawDays: 'Terças, Quintas e Sábados às 20h',
  },
  lotofacil: {
    id: 'lotofacil',
    slug: 'lotofacil',
    name: 'Lotofácil',
    fullName: 'Lotofácil',
    description: 'Como o próprio nome diz: fácil de apostar e muitas chances de ganhar.',
    primaryColor: '#930089',
    badgeBg: 'bg-fuchsia-500/10 dark:bg-fuchsia-400/20 text-fuchsia-700 dark:text-fuchsia-300 border-fuchsia-300 dark:border-fuchsia-600',
    badgeText: 'text-fuchsia-700 dark:text-fuchsia-300',
    ballBg: 'bg-gradient-to-br from-fuchsia-600 to-purple-800 text-white shadow-fuchsia-500/30',
    accentBorder: 'border-fuchsia-500',
    minNumber: 1,
    maxNumber: 25,
    defaultPickQuantity: 15,
    allowedPickQuantities: [15, 16, 17, 18, 19, 20],
    howToPlay: 'Marque entre 15 e 20 números dentre os 25 disponíveis. Fatura prêmio acertando 11, 12, 13, 14 ou 15 números.',
    drawDays: 'Segunda a Sábado às 20h',
  },
  quina: {
    id: 'quina',
    slug: 'quina',
    name: 'Quina',
    fullName: 'Quina',
    description: 'Sorteios diários de segunda a sábado e prêmios que acumulam rápido.',
    primaryColor: '#260085',
    badgeBg: 'bg-indigo-500/10 dark:bg-indigo-400/20 text-indigo-700 dark:text-indigo-300 border-indigo-300 dark:border-indigo-600',
    badgeText: 'text-indigo-700 dark:text-indigo-300',
    ballBg: 'bg-gradient-to-br from-indigo-600 to-blue-800 text-white shadow-indigo-500/30',
    accentBorder: 'border-indigo-500',
    minNumber: 1,
    maxNumber: 80,
    defaultPickQuantity: 5,
    allowedPickQuantities: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    howToPlay: 'Concorra marcando de 5 a 15 números dentre os 80 disponíveis. Ganhe prêmios acertando 2, 3, 4 ou 5 números.',
    drawDays: 'Segunda a Sábado às 20h',
  },
  lotomania: {
    id: 'lotomania',
    slug: 'lotomania',
    name: 'Lotomania',
    fullName: 'Lotomania',
    description: 'Escolha 50 números e ganhe acertando de 15 a 20 números ou NENHUM.',
    primaryColor: '#f78100',
    badgeBg: 'bg-amber-500/10 dark:bg-amber-400/20 text-amber-700 dark:text-amber-300 border-amber-300 dark:border-amber-600',
    badgeText: 'text-amber-700 dark:text-amber-300',
    ballBg: 'bg-gradient-to-br from-amber-500 to-orange-700 text-white shadow-amber-500/30',
    accentBorder: 'border-amber-500',
    minNumber: 0,
    maxNumber: 99,
    defaultPickQuantity: 50,
    allowedPickQuantities: [50],
    howToPlay: 'Você escolhe 50 números e ganha se acertar 20, 19, 18, 17, 16, 15 ou nenhum número.',
    drawDays: 'Segundas, Quartas e Sextas às 20h',
  },
  maismilionaria: {
    id: 'maismilionaria',
    slug: 'mais-milionaria',
    name: '+Milionária',
    fullName: '+Milionária',
    description: 'A loteria com prêmio mínimo de R$ 10 Milhões e matriz de números e trevos.',
    primaryColor: '#0c6c4c',
    badgeBg: 'bg-teal-500/10 dark:bg-teal-400/20 text-teal-700 dark:text-teal-300 border-teal-300 dark:border-teal-600',
    badgeText: 'text-teal-700 dark:text-teal-300',
    ballBg: 'bg-gradient-to-br from-teal-600 to-emerald-800 text-white shadow-teal-500/30',
    accentBorder: 'border-teal-500',
    minNumber: 1,
    maxNumber: 50,
    defaultPickQuantity: 6,
    allowedPickQuantities: [6, 7, 8, 9, 10, 11, 12],
    hasTrevos: true,
    minTrevos: 2,
    maxTrevos: 6,
    howToPlay: 'Escolha no mínimo 6 números de 1 a 50 e 2 trevos numerados de 1 a 6. São 10 faixas de premiação.',
    drawDays: 'Quartas e Sábados às 20h',
  },
  duplasena: {
    id: 'duplasena',
    slug: 'dupla-sena',
    name: 'Dupla Sena',
    fullName: 'Dupla Sena',
    description: 'Com o mesmo bilhete você tem 2 sorteios e o dobro de chances de ser premiado.',
    primaryColor: '#a61322',
    badgeBg: 'bg-rose-500/10 dark:bg-rose-400/20 text-rose-700 dark:text-rose-300 border-rose-300 dark:border-rose-600',
    badgeText: 'text-rose-700 dark:text-rose-300',
    ballBg: 'bg-gradient-to-br from-rose-600 to-red-800 text-white shadow-rose-500/30',
    accentBorder: 'border-rose-500',
    minNumber: 1,
    maxNumber: 50,
    defaultPickQuantity: 6,
    allowedPickQuantities: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    isDuplaSena: true,
    howToPlay: 'Escolha de 6 a 15 números entre 50 disponíveis. Um mesmo bilhete concorre a dois sorteios no mesmo concurso.',
    drawDays: 'Segundas, Quartas e Sextas às 20h',
  },
  diadesorte: {
    id: 'diadesorte',
    slug: 'dia-de-sorte',
    name: 'Dia de Sorte',
    fullName: 'Dia de Sorte',
    description: 'Aposte seus números favoritos e o Mês de Sorte para ganhar.',
    primaryColor: '#cb852b',
    badgeBg: 'bg-yellow-500/10 dark:bg-yellow-400/20 text-yellow-800 dark:text-yellow-300 border-yellow-300 dark:border-yellow-600',
    badgeText: 'text-yellow-800 dark:text-yellow-300',
    ballBg: 'bg-gradient-to-br from-amber-500 to-yellow-700 text-white shadow-yellow-500/30',
    accentBorder: 'border-yellow-500',
    minNumber: 1,
    maxNumber: 31,
    defaultPickQuantity: 7,
    allowedPickQuantities: [7, 8, 9, 10, 11, 12, 13, 14, 15],
    hasMesSorte: true,
    howToPlay: 'Escolha de 7 a 15 números dentre os 31 e mais 1 Mês de Sorte. Premiações com 4, 5, 6 ou 7 acertos + Mês do Sorteio.',
    drawDays: 'Terças, Quintas e Sábados às 20h',
  },
  timemania: {
    id: 'timemania',
    slug: 'timemania',
    name: 'Timemania',
    fullName: 'Timemania',
    description: 'Ajude seu clube do coração e concorra a prêmios milionários toda semana.',
    primaryColor: '#059669',
    badgeBg: 'bg-lime-500/10 dark:bg-lime-400/20 text-lime-800 dark:text-lime-300 border-lime-300 dark:border-lime-600',
    badgeText: 'text-lime-800 dark:text-lime-300',
    ballBg: 'bg-gradient-to-br from-yellow-400 to-lime-600 text-slate-900 font-extrabold shadow-lime-500/30',
    accentBorder: 'border-lime-500',
    minNumber: 1,
    maxNumber: 80,
    defaultPickQuantity: 10,
    allowedPickQuantities: [10],
    hasTimeCoracao: true,
    howToPlay: 'Você escolhe 10 números entre os 80 disponíveis e um Time do Coração. São sorteados 7 números e 1 time.',
    drawDays: 'Terças, Quintas e Sábados às 20h',
  },
  supersete: {
    id: 'supersete',
    slug: 'super-sete',
    name: 'Super Sete',
    fullName: 'Super Sete',
    description: 'A loteria em colunas: escolha seus palpites coluna por coluna.',
    primaryColor: '#00875a',
    badgeBg: 'bg-emerald-500/10 dark:bg-emerald-400/20 text-emerald-800 dark:text-emerald-300 border-emerald-300 dark:border-emerald-600',
    badgeText: 'text-emerald-800 dark:text-emerald-300',
    ballBg: 'bg-gradient-to-br from-emerald-600 to-teal-700 text-white shadow-emerald-500/30',
    accentBorder: 'border-emerald-500',
    minNumber: 0,
    maxNumber: 9,
    defaultPickQuantity: 7,
    allowedPickQuantities: [7, 8, 9, 10, 11, 12, 13, 14],
    hasColumns: true,
    howToPlay: 'O volante contém 7 colunas numeradas de 0 a 9. Marque no mínimo 1 número por coluna (máximo de 3 números por coluna).',
    drawDays: 'Segundas, Quartas e Sextas às 20h',
  },
  federal: {
    id: 'federal',
    slug: 'federal',
    name: 'Federal',
    fullName: 'Loteria Federal',
    description: 'A mais tradicional loteria brasileira, com bilhetes pré-numerados e premiações fixas por extração.',
    primaryColor: '#104085',
    badgeBg: 'bg-sky-500/10 dark:bg-sky-400/20 text-sky-800 dark:text-sky-300 border-sky-300 dark:border-sky-600',
    badgeText: 'text-sky-800 dark:text-sky-300',
    ballBg: 'bg-gradient-to-br from-sky-600 to-blue-800 text-white shadow-sky-500/30',
    accentBorder: 'border-sky-500',
    minNumber: 0,
    maxNumber: 99999,
    defaultPickQuantity: 1,
    allowedPickQuantities: [1],
    isFederal: true,
    howToPlay: 'Na Loteria Federal não há marcação de dezenas em volante. Você adquire um bilhete já emitido com número de 5 dígitos (inteiro ou frações) nas lotéricas ou no site oficial da Caixa. São sorteados 5 prêmios principais em cada extração, além de prêmios por aproximação, milhar, centenas e dezenas. As faixas de premiação são fixas e a modalidade não acumula.',
    drawDays: 'Quartas e Sábados às 19h',
  },
};

export const LOTTERIES_LIST = Object.values(LOTTERIES_CONFIG);
